Glp week4
gui2de/econ490-fall22 pull request #67
Opened 2022-10-04 05:54 UTC by geena-panzitta

2022-10-04 16:41 UTC, BeaLeydier commented on Geena - geena-panzitta/GLP_week4assignment.do
> +label variable pixel_payout_min "Minimum payout within pixel"
This is the wrong variable label

```suggestion
label variable pixel_payout_min "Maximum payout within pixel"
```

2022-10-04 16:42 UTC, BeaLeydier commented on Geena - geena-panzitta/GLP_week4assignment.do
> +label variable pixel_max "Maximum pixel within village"
```suggestion
bysort village: egen pixelmin = min(pixelnumerical)
bysort village: egen pixelmax = max(pixelnumerical)
label variable pixel_min "Minimum pixel within village"
label variable pixel_max "Maximum pixel within village"
```

2022-10-04 16:42 UTC, BeaLeydier commented on Geena - geena-panzitta/GLP_week4assignment.do
> +use `allstudents', clear
this doesn't run

2022-10-04 16:43 UTC, BeaLeydier requested changes
See in line comments

2022-10-10 01:33 UTC, shailyacharya approved these changes

2022-10-10 01:33 UTC, shailyacharya commented on Geena - geena-panzitta/GLP_week4assignment.do
> +label variable pixel_consistent "Are payouts consistent without pixel?"
Nice use of variable labels-- you reminded me that I should probably add this to my code as well!

2022-10-10 01:33 UTC, shailyacharya commented on Geena - geena-panzitta/GLP_week4assignment.do
> +use `allstudents', clear
I am running into the same issue as Bea!

2022-10-10 01:33 UTC, shailyacharya commented on Geena - geena-panzitta/GLP_week4assignment.do
> +foreach i in $students {
Is there a reason why you defined students as a global, instead of as a local?

2022-10-25 18:21 UTC, merged